### ISSUE TITLE
Deploying .secrets and .Rprofile to Posit Connect?

### ISSUE THREAD

**Issue by jessicaguo** [JosiahParry/rsc-gsheets#3]
Hi there! Thanks for this handy tutorial. I do have a question about how to publish the .secrets and .Rprofile to Posit Connect. When I go to publish (in my case a shiny app, within a folder of a larger project), I cannot select the hidden files from one level up to go into the published bundle. 

One solution is to put the app into a separate repo. Before I try this, is there another way to include those files for publishing?

**Comment by JosiahParry** [comment]
Hey! I no longer work at RStudio (now Posit) so I am not tooo sure how Connect works these days. 

However, I would recommend making the shiny app be its own stand alone thing. It shouldn't have to be in its own repo, but it should be self sufficient (work without navigating outside of its root directory). It sounds like you have secrets in a parent locations which will not work as you have found out. 

Wha I would recommend is using an environment variable and store that in your `.Renviron` (DO NOT PUBLISH THIS) and then use `Sys.getenv("GOOGLESHEETS_TOKEN")` or whatever, whenever its called / needed. Then you can use the environment variable feature of connect to provide secrets that way. 

Do not upload the .secret file either. If someone finds a way to access the bundle then they can get your credentials which you do not want!

**Comment by jessicaguo** [comment]
Thanks Josiah! I ended up moving the app to a new standalone folder and following your original instructions, plus a small change to reflect the new function googlesheets4::gs4_auth(). Thanks for the reminder to suppress the .secret file from git tracking while simultaneously publishing to Posit Connect!
